#!/bin/sh
#
# Xcode Cloud post-clone hook for the Breeze mobile app.
#
# WHY THIS EXISTS
# ---------------
# `apps/mobile/ios` is generated by `expo prebuild`, not committed (Continuous
# Native Generation — see apps/mobile/.gitignore). A fresh Xcode Cloud clone
# therefore contains no `BreezeRMM.xcworkspace`, and the build fails before it
# starts with:
#
#     Workspace BreezeRMM.xcworkspace does not exist at
#     apps/mobile/ios/BreezeRMM.xcworkspace
#
# Xcode Cloud runs this script immediately after cloning and before resolving
# the workspace, so this is the hook that has to produce the native project.
#
# WHY IT LIVES HERE
# -----------------
# Xcode Cloud looks for `ci_scripts` as a sibling of the .xcworkspace, which
# puts it inside the ignored `ios/` directory. `.gitignore` re-includes exactly
# this one subdirectory; everything else under `ios/` stays generated.
#
# WHY IT RE-EXECS ITSELF
# ----------------------
# `expo prebuild` replaces the whole `ios/` directory — including `ci_scripts`,
# and including this file — even without `--clean`. `sh` reads a script
# incrementally rather than loading it whole, so letting the file vanish
# mid-execution is undefined behaviour. Verified locally: prebuild deletes
# `ios/ci_scripts` outright. So the first thing this does is copy itself
# somewhere prebuild cannot reach and hand over to that copy.
#
# `sh`, not `bash`, and no `pipefail`: Xcode Cloud executes these with /bin/sh.

set -eu

# ---------------------------------------------------------------------------
# Resolve the checkout root BEFORE any re-exec, while $0 is still the real path.
# CI_PRIMARY_REPOSITORY_PATH is Xcode Cloud's checkout root; CI_WORKSPACE is the
# older name. The fallback walks up from ios/ci_scripts -> ios -> mobile ->
# apps -> repo root.
# ---------------------------------------------------------------------------
if [ -z "${BREEZE_CI_REPO_ROOT:-}" ]; then
  BREEZE_CI_REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-${CI_WORKSPACE:-}}"
  if [ -z "$BREEZE_CI_REPO_ROOT" ]; then
    BREEZE_CI_REPO_ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
  fi
  export BREEZE_CI_REPO_ROOT
fi

# Hand over to a copy outside ios/, once.
if [ "${BREEZE_CI_REEXEC:-}" != "1" ]; then
  SELF_COPY="$(mktemp -t breeze_ci_post_clone)"
  cat "$0" > "$SELF_COPY"
  BREEZE_CI_REEXEC=1
  export BREEZE_CI_REEXEC
  echo "--- ci_post_clone: re-exec from $SELF_COPY (prebuild deletes this script's directory)"
  exec sh "$SELF_COPY"
fi

REPO_ROOT="$BREEZE_CI_REPO_ROOT"
cd "$REPO_ROOT"
echo "--- ci_post_clone: generating the native iOS project"
echo "--- repo root: $REPO_ROOT"

# ---------------------------------------------------------------------------
# Toolchain. The Xcode Cloud image ships neither Node nor (reliably) CocoaPods,
# but does ship Homebrew.
# ---------------------------------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
  echo "--- installing Node"
  brew install node@22
  # Keg-only formula: not linked into PATH automatically.
  PATH="$(brew --prefix node@22)/bin:$PATH"
  export PATH
fi
echo "--- node $(node --version)"

# pnpm at the exact version pinned by the root package.json packageManager field.
corepack enable
corepack prepare --activate
echo "--- pnpm $(pnpm --version)"

if ! command -v pod >/dev/null 2>&1; then
  echo "--- installing CocoaPods"
  brew install cocoapods
fi

# Only the mobile package and its workspace dependencies. The API and web apps
# are irrelevant here and pulling them in roughly triples install time.
echo "--- installing JS dependencies"
pnpm install --filter breeze-mobile... --frozen-lockfile

# ---------------------------------------------------------------------------
# Build variables. Two of these gate a RELEASE build and make app.config.js
# throw when unset (src/config/sentryDsn.js, src/config/apiUrl.js). Xcode build
# phases do not inherit this script's environment, so whatever the Xcode Cloud
# workflow sets has to be written to the .env file the config phase reads.
#
# Nothing is invented: if the workflow sets none of them, no file is written and
# the build fails loudly at the config phase, which is the intended behaviour.
# Written via a temp file so an existing .env is never truncated to nothing.
# ---------------------------------------------------------------------------
ENV_FILE="$REPO_ROOT/apps/mobile/.env"
ENV_TMP="$ENV_FILE.ci_post_clone.tmp"
: > "$ENV_TMP"
for VAR in EXPO_PUBLIC_API_URL EXPO_PUBLIC_SENTRY_DSN EXPO_PUBLIC_POSTHOG_KEY \
           EXPO_PUBLIC_POSTHOG_HOST BREEZE_MOBILE_ALLOW_NO_SENTRY \
           BREEZE_MOBILE_ALLOW_PRIVATE_API_URL BREEZE_ASSOCIATED_DOMAINS; do
  eval "VALUE=\${$VAR:-}"
  if [ -n "$VALUE" ]; then
    echo "$VAR=$VALUE" >> "$ENV_TMP"
    # Deliberately not echoing values — the DSN is not a secret, but the
    # PostHog key and anything added here later may be.
    echo "--- .env: set $VAR"
  fi
done
if [ -s "$ENV_TMP" ]; then
  mv "$ENV_TMP" "$ENV_FILE"
else
  rm -f "$ENV_TMP"
  echo "--- .env: workflow set none of the build variables, leaving any existing file alone"
fi

# ---------------------------------------------------------------------------
# Symbolication. The DSN only makes events ARRIVE; making them READABLE needs
# source maps and dSYMs, which the @sentry/react-native/expo plugin uploads from
# two Xcode build phases using SENTRY_AUTH_TOKEN.
#
# Unlike the DSN this is a GENUINE SECRET, so it goes in its own gitignored file
# rather than .env — .env values are compiled into the JS bundle and would ship
# inside the IPA. Mark it "secret" in the Xcode Cloud workflow so it is redacted
# from build logs.
#
# Missing it does not fail the build, and that is exactly the hazard: events
# still arrive, but every JS frame is a minified bundle offset and native
# crashes have no symbols. It looks like working telemetry until someone needs
# to read a crash — the same "looks like it worked" class as shipping with no
# DSN at all. So warn loudly instead of passing over it in silence.
# ---------------------------------------------------------------------------
SENTRY_ENV_FILE="$REPO_ROOT/apps/mobile/.env.sentry-build-plugin"
if [ -n "${SENTRY_AUTH_TOKEN:-}" ]; then
  # Never echoed, only its presence.
  printf 'SENTRY_AUTH_TOKEN=%s\n' "$SENTRY_AUTH_TOKEN" > "$SENTRY_ENV_FILE"
  chmod 600 "$SENTRY_ENV_FILE"
  echo "--- .env.sentry-build-plugin: SENTRY_AUTH_TOKEN written"
elif [ -f "$SENTRY_ENV_FILE" ]; then
  echo "--- .env.sentry-build-plugin: workflow set no SENTRY_AUTH_TOKEN, leaving existing file alone"
else
  echo "--- WARNING: SENTRY_AUTH_TOKEN is not set. This build will report crashes" >&2
  echo "---          but WITHOUT source maps or dSYMs, so every JS frame will be a" >&2
  echo "---          minified bundle offset and native crashes will have no symbols." >&2
  echo "---          Set it as a secret environment variable on the Xcode Cloud" >&2
  echo "---          workflow (scopes: project:releases, org:read)." >&2
fi

# ---------------------------------------------------------------------------
# Generate ios/. Never `--clean`: it is even more destructive than the default,
# and the default already replaces this script's directory.
# ---------------------------------------------------------------------------
echo "--- expo prebuild"
cd "$REPO_ROOT/apps/mobile"
npx expo prebuild --platform ios --no-install

# ---------------------------------------------------------------------------
# Hermes. react-native's hermes-engine.podspec decides at `pod install` time
# whether to download a prebuilt Hermes or build it from source, by probing
# Maven with a bare `curl -I -L`. When that probe fails for ANY reason — the
# 2026-09-09 case: Maven Central now 301s the tarballs to repo.reactnative.dev,
# where the .tar.gz files 404 while their .sha1 files do not — the podspec
# silently falls back to a from-source build, which needs cmake, which the
# Xcode Cloud image does not ship. The build then dies inside the podspec with
#
#     [!] Unable to locate the executable `cmake`
#
# So fetch the prebuilt tarball here, on our own terms: try Maven, then an
# optional mirror the workflow can point at, verify the sha1 against Maven's
# published checksum, and hand the file to the podspec via
# HERMES_ENGINE_TARBALL_PATH. If every source fails, install cmake so the
# from-source fallback can at least complete, and say so loudly — it adds
# roughly half an hour to the build.
#
# Workflow variables (all optional):
#   BREEZE_HERMES_TARBALL_URL   mirror URL for the exact release tarball
#   BREEZE_HERMES_TARBALL_SHA1  its sha1, required only when Maven's .sha1 is
#                               unreachable
#   RCT_HERMES_V1_ENABLED=0     selects the legacy Hermes version name, same
#                               switch the podspec reads
# ---------------------------------------------------------------------------
HERMES_PROPS="$REPO_ROOT/apps/mobile/node_modules/react-native/sdks/hermes-engine/version.properties"
if [ "${RCT_HERMES_V1_ENABLED:-1}" = "0" ]; then
  HERMES_VERSION="$(sed -n 's/^HERMES_VERSION_NAME=//p' "$HERMES_PROPS" 2>/dev/null || true)"
else
  HERMES_VERSION="$(sed -n 's/^HERMES_V1_VERSION_NAME=//p' "$HERMES_PROPS" 2>/dev/null || true)"
fi
if [ -z "$HERMES_VERSION" ]; then
  echo "ci_post_clone: could not read the Hermes version from $HERMES_PROPS (missing file, or the key is absent)" >&2
  exit 1
fi
echo "--- hermes: prebuilt version $HERMES_VERSION"

HERMES_MAVEN_BASE="https://repo1.maven.org/maven2/com/facebook/hermes/hermes-ios/$HERMES_VERSION"
HERMES_TARBALL_NAME="hermes-ios-$HERMES_VERSION-hermes-ios-release.tar.gz"
HERMES_TARBALL="$(mktemp -d -t breeze_hermes)/$HERMES_TARBALL_NAME"

# Expected checksum: the workflow's value wins; otherwise Maven's .sha1.
HERMES_SHA1="${BREEZE_HERMES_TARBALL_SHA1:-}"
if [ -z "$HERMES_SHA1" ]; then
  HERMES_SHA1="$(curl -fsSL --retry 3 "$HERMES_MAVEN_BASE/$HERMES_TARBALL_NAME.sha1" 2>/dev/null | head -c 40 || true)"
fi
# A checksum that is not exactly 40 hex characters (an HTML error page, a
# pasted value with whitespace) must read as "no checksum", not as a mismatch
# that looks like a tampered tarball. Same guard react-native's own
# fetch_maven_sha1 applies.
HERMES_SHA1="$(printf '%s' "$HERMES_SHA1" | tr 'A-Z' 'a-z')"
case "$HERMES_SHA1" in
  ????????????????????????????????????????) case "$HERMES_SHA1" in *[!0-9a-f]*) HERMES_SHA1="" ;; esac ;;
  *) HERMES_SHA1="" ;;
esac
[ -n "$HERMES_SHA1" ] || echo "--- hermes: no usable sha1 for $HERMES_TARBALL_NAME; any download will be refused" >&2

# Google's Maven Central mirror serves the same bytes directly, without the
# redirect that is broken on the primary. It is transport only: the sha1 gate
# above still comes from Maven itself.
HERMES_GCS_BASE="https://maven-central.storage-download.googleapis.com/maven2/com/facebook/hermes/hermes-ios/$HERMES_VERSION"

hermes_fetch() {
  # $1 = URL. Succeeds only when the download completes AND the sha1 matches.
  rm -f "$HERMES_TARBALL"
  if ! curl -fsSL --retry 3 --retry-all-errors -A "react-native-$HERMES_VERSION" -o "$HERMES_TARBALL" "$1"; then
    echo "--- hermes: $1 unavailable"
    return 1
  fi
  if [ -z "$HERMES_SHA1" ]; then
    echo "--- hermes: downloaded $1 but no sha1 is known to verify it against; refusing it" >&2
    return 1
  fi
  GOT="$(shasum -a 1 "$HERMES_TARBALL" | cut -d' ' -f1)"
  if [ "$GOT" != "$HERMES_SHA1" ]; then
    echo "--- hermes: sha1 mismatch for $1 (want $HERMES_SHA1, got $GOT); refusing it" >&2
    return 1
  fi
  return 0
}

HERMES_READY=0
if hermes_fetch "$HERMES_MAVEN_BASE/$HERMES_TARBALL_NAME"; then
  HERMES_READY=1
elif hermes_fetch "$HERMES_GCS_BASE/$HERMES_TARBALL_NAME"; then
  HERMES_READY=1
elif [ -n "${BREEZE_HERMES_TARBALL_URL:-}" ] && hermes_fetch "$BREEZE_HERMES_TARBALL_URL"; then
  HERMES_READY=1
fi

if [ "$HERMES_READY" = "1" ]; then
  # A local tarball is used verbatim for every configuration (the podspec only
  # adds its per-configuration swap for Maven downloads). Correct for the
  # Archive/Release action this workflow runs; a Debug action in the same
  # workflow would link release Hermes, which builds and runs but has no CDP
  # inspector. Gate this on CI_XCODEBUILD_ACTION if Debug actions are added.
  echo "--- hermes: using verified prebuilt tarball ($HERMES_SHA1)"
  HERMES_ENGINE_TARBALL_PATH="$HERMES_TARBALL"
  export HERMES_ENGINE_TARBALL_PATH
else
  echo "--- WARNING: no prebuilt Hermes $HERMES_VERSION could be fetched and verified." >&2
  echo "---          Falling back to building Hermes from source. This works but adds" >&2
  echo "---          roughly 30 minutes. To skip it, host the release tarball somewhere" >&2
  echo "---          reachable and set BREEZE_HERMES_TARBALL_URL on the workflow." >&2
  if ! command -v cmake >/dev/null 2>&1; then
    echo "--- installing cmake (required by the from-source Hermes build)"
    brew install cmake
  fi
fi

echo "--- pod install"
cd "$REPO_ROOT/apps/mobile/ios"
pod install

if [ ! -d "BreezeRMM.xcworkspace" ]; then
  echo "ci_post_clone: prebuild finished but BreezeRMM.xcworkspace is still missing" >&2
  exit 1
fi

# Put ci_scripts back so the tree matches what was cloned. Not needed for this
# build (Xcode Cloud already read the script), but it keeps a re-run of the
# same checkout working and makes the deletion non-surprising to anyone poking
# at the build machine.
if [ ! -d "$REPO_ROOT/apps/mobile/ios/ci_scripts" ]; then
  echo "--- restoring ci_scripts (prebuild removed it)"
  mkdir -p "$REPO_ROOT/apps/mobile/ios/ci_scripts"
  cp "$0" "$REPO_ROOT/apps/mobile/ios/ci_scripts/ci_post_clone.sh"
  chmod 755 "$REPO_ROOT/apps/mobile/ios/ci_scripts/ci_post_clone.sh"
fi

echo "--- ci_post_clone: done, workspace generated"
