package launchdplist

import (
	"os"
	"testing"
)

const wantDesktopHelperUser = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.breeze.desktop-helper-user</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/breeze-desktop-helper</string>
        <string>--context</string>
        <string>user_session</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>LimitLoadToSessionType</key>
    <string>Aqua</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
`

const wantDesktopHelperLoginWindow = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.breeze.desktop-helper-loginwindow</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/breeze-desktop-helper</string>
        <string>--context</string>
        <string>login_window</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>LimitLoadToSessionType</key>
    <string>LoginWindow</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
`

// TestRenderedPlistsMatchGolden pins the exact XML the three former
// hand-synced copies agreed on before consolidation (#4379). A diff here
// means a plist VALUE changed, not just its source of truth.
func TestRenderedPlistsMatchGolden(t *testing.T) {
	if DesktopHelperUser != wantDesktopHelperUser {
		t.Errorf("DesktopHelperUser mismatch:\ngot:\n%s\nwant:\n%s", DesktopHelperUser, wantDesktopHelperUser)
	}
	if DesktopHelperLoginWindow != wantDesktopHelperLoginWindow {
		t.Errorf("DesktopHelperLoginWindow mismatch:\ngot:\n%s\nwant:\n%s", DesktopHelperLoginWindow, wantDesktopHelperLoginWindow)
	}
}

// TestStaticPlistFilesMatchRendered guards the copy build-pkg.sh ships:
// agent/service/launchd/*.plist. Those files aren't generated by this
// package (build-pkg.sh just copies them from disk), so they can silently
// drift from the Go-rendered source of truth used by service_cmd_darwin.go
// and heartbeat/handlers_desktop_helper.go. This test fails CI the moment
// they diverge.
func TestStaticPlistFilesMatchRendered(t *testing.T) {
	cases := []struct {
		path string
		want string
	}{
		{"../../service/launchd/com.breeze.desktop-helper-user.plist", DesktopHelperUser},
		{"../../service/launchd/com.breeze.desktop-helper-loginwindow.plist", DesktopHelperLoginWindow},
	}
	for _, c := range cases {
		data, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("reading %s: %v", c.path, err)
		}
		if string(data) != c.want {
			t.Errorf("%s has drifted from the rendered plist:\non-disk:\n%s\nrendered:\n%s", c.path, data, c.want)
		}
	}
}
